J = 0.01;
b = 0.1;
K = 0.01;
R = 1;
L = 0.5;
T_load = 0.1;
s = tf('s');
P_motor = K / ((J*s + b)*(L*s + R) + K^2);
A = [0, 1, 0; 0, -b/J, K/J; 0, -K/L, -R/L];
B = [0; 0; 1/L];
C = eye(3);
D = zeros(3, 1);
sys = ss(A, B, C, D);
t = 0:0.01:10;
u = ones(size(t));
[y, t, x] = lsim(sys, u, t);
subplot(2, 1, 1);
plot(t, y(:, 1), 'b', t, y(:, 2), 'r', t, y(:, 3), 'g');
xlabel('Time (s)');
ylabel('Motor Variables');
legend('Position (rad)', 'Velocity (rad/s)', 'Current (A)');
title('Motor Drive Inverter System Digital Twin Response');
grid on;